-- ===============================
-- File: AutoPurchaseSystem_Tables.sql
-- Purpose: Drop & Create Tables
-- ===============================

IF DB_ID('AUTO_PURCHASE_SYSTEM') IS NULL
BEGIN
    CREATE DATABASE AUTO_PURCHASE_SYSTEM;
END
GO

USE AUTO_PURCHASE_SYSTEM;
GO

-- Drop tables theo thứ tự tránh lỗi FK
IF OBJECT_ID('dbo.T_PURCHASE_RESULTS', 'U') IS NOT NULL DROP TABLE dbo.T_PURCHASE_RESULTS;
IF OBJECT_ID('dbo.T_PURCHASE_SCHEDULES', 'U') IS NOT NULL DROP TABLE dbo.T_PURCHASE_SCHEDULES;
IF OBJECT_ID('dbo.T_LICENSE_ASSIGNMENTS', 'U') IS NOT NULL DROP TABLE dbo.T_LICENSE_ASSIGNMENTS;
IF OBJECT_ID('dbo.T_PROXIES', 'U') IS NOT NULL DROP TABLE dbo.T_PROXIES;
IF OBJECT_ID('dbo.T_LICENSES', 'U') IS NOT NULL DROP TABLE dbo.T_LICENSES;
IF OBJECT_ID('dbo.T_CLIENTS', 'U') IS NOT NULL DROP TABLE dbo.T_CLIENTS;
IF OBJECT_ID('dbo.T_ADMIN_USERS', 'U') IS NOT NULL DROP TABLE dbo.T_ADMIN_USERS;
IF OBJECT_ID('dbo.T_LOGS', 'U') IS NOT NULL DROP TABLE dbo.T_LOGS;

-- Bảng Clients
CREATE TABLE T_CLIENTS (
    CLIENT_ID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    MACHINE_ID NVARCHAR(255) NOT NULL UNIQUE,
    CREATED_AT DATETIME DEFAULT GETUTCDATE()
);

-- Bảng Licenses
CREATE TABLE T_LICENSES (
    LICENSE_ID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    LICENSE_KEY NVARCHAR(50) NOT NULL UNIQUE,
    CREATED_AT DATETIME DEFAULT GETUTCDATE(),
    EXPIRED_AT DATETIME NOT NULL,
    IS_ACTIVE BIT DEFAULT 1
);

-- Bảng LicenseAssignments
CREATE TABLE T_LICENSE_ASSIGNMENTS (
    ASSIGNMENT_ID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    LICENSE_ID UNIQUEIDENTIFIER NOT NULL,
    CLIENT_ID UNIQUEIDENTIFIER NOT NULL,
    IS_LOGGED_IN BIT DEFAULT 0,
    LAST_LOGIN_AT DATETIME NULL,
    ASSIGNED_AT DATETIME DEFAULT GETUTCDATE(),
    FOREIGN KEY (LICENSE_ID) REFERENCES T_LICENSES(LICENSE_ID) ON DELETE CASCADE,
    FOREIGN KEY (CLIENT_ID) REFERENCES T_CLIENTS(CLIENT_ID) ON DELETE CASCADE
);

-- Bảng Proxies
CREATE TABLE T_PROXIES (
    PROXY_ID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    PROXY_ADDRESS NVARCHAR(255) NOT NULL,
    ACCOUNT_USERNAME NVARCHAR(255) NULL,
    ACCOUNT_PASSWORD NVARCHAR(255) NULL,
    CREATED_AT DATETIME DEFAULT GETUTCDATE()
);

-- Bảng PurchaseSchedules
CREATE TABLE T_PURCHASE_SCHEDULES (
    SCHEDULE_ID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    CLIENT_ID UNIQUEIDENTIFIER NOT NULL,
    PRODUCT_ID NVARCHAR(100) NOT NULL,
    QUANTITY INT NOT NULL,
    PURCHASE_TIME DATETIME NOT NULL,
    COOKIE NVARCHAR(MAX) NULL,
    PROXY_ID UNIQUEIDENTIFIER NULL,
    STATUS NVARCHAR(50) DEFAULT 'PENDING',
    CREATED_AT DATETIME DEFAULT GETUTCDATE(),
    FOREIGN KEY (CLIENT_ID) REFERENCES T_CLIENTS(CLIENT_ID) ON DELETE CASCADE,
    FOREIGN KEY (PROXY_ID) REFERENCES T_PROXIES(PROXY_ID)
);

-- Bảng PurchaseResults
CREATE TABLE T_PURCHASE_RESULTS (
    RESULT_ID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    SCHEDULE_ID UNIQUEIDENTIFIER NOT NULL,
    IS_SUCCESS BIT NOT NULL,
    RESPONSE_MESSAGE NVARCHAR(MAX),
    CREATED_AT DATETIME DEFAULT GETUTCDATE(),
    FOREIGN KEY (SCHEDULE_ID) REFERENCES T_PURCHASE_SCHEDULES(SCHEDULE_ID) ON DELETE CASCADE
);

-- Bảng AdminUsers
CREATE TABLE T_ADMIN_USERS (
    ADMIN_ID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    USERNAME NVARCHAR(50) NOT NULL UNIQUE,
    PASSWORD_HASH NVARCHAR(255) NOT NULL,
    CREATED_AT DATETIME DEFAULT GETUTCDATE()
);

-- Bảng Logs
CREATE TABLE T_LOGS (
    LOG_ID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    LOG_MESSAGE NVARCHAR(MAX) NOT NULL,
    CREATED_AT DATETIME DEFAULT GETUTCDATE()
);
